# Generated by Django 4.2.2 on 2023-06-27 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movies',
            name='img',
            field=models.ImageField(default='imagefield', upload_to='images'),
            preserve_default=False,
        ),
    ]
